---
# tasks file for containerd
#
#
#
- name: mkdir for containerd
  file:
    path: /etc/containerd
    state: directory
    
- name: unarchive containerd
  unarchive:
    src: '{{item}}'
    dest: /
  with_fileglob:
  - "bin/cri-containerd-cni-*"



- name: push containerd config file
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml

- name: start containerd
  systemd:
    name: containerd
    state: started
    enabled: yes
    daemon_reload: yes

